# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('min_teams_per_match', models.IntegerField()),
                ('max_teams_per_match', models.IntegerField(blank=True, null=True)),
                ('min_players_per_team', models.IntegerField()),
                ('max_players_per_team', models.IntegerField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='AdhocTeam',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ranking', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'adhoc_team',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'player',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('datetime', models.IntegerField(blank=True, null=True)),
                ('validated', models.IntegerField(blank=True, null=True)),
                ('submittor', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'result',
            },
        ),
        migrations.CreateModel(
            name='ResultSet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'result_set',
            },
        ),
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('min_skill_range', models.FloatField()),
                ('max_skill_range', models.FloatField()),
                ('initial_mean', models.FloatField()),
                ('initial_std_dev', models.FloatField()),
                ('dynamics_factor', models.FloatField()),
                ('skill_chain', models.FloatField()),
                ('draw_chance', models.FloatField()),
            ],
            options={
                'managed': False,
                'db_table': 'skill_type',
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.IntegerField(blank=True, null=True)),
                ('mu', models.FloatField(blank=True, null=True)),
                ('sigma', models.FloatField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='previous.Activity')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='previous.Player')),
            ],
            options={
                'managed': False,
                'db_table': 'ranking',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ranking',
            unique_together=set([('player', 'activity')]),
        ),
        migrations.CreateModel(
            name='ResultSetMember',
            fields=[
                ('result_set', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, to='previous.ResultSet')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='previous.Player')),
            ],
            options={
                'managed': False,
                'db_table': 'result_set_member',
            },
        ),
        migrations.CreateModel(
            name='SkillHistory',
            fields=[
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='previous.Result')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, to='previous.Player')),
                ('activity_id', models.TextField(blank=True, null=True)),
                ('mu', models.FloatField(blank=True, null=True)),
                ('sigma', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'skill_history',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='previous.AdhocTeam')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, to='previous.Player')),
                ('validated', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'team_member',
            },
        ),
    ]
