# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-21 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previous', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            'Result', 'GameSession'
        ),
        migrations.AlterModelOptions(
            name='gamesession',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='gamesession',
            table='gamesession',
        ),
    ]
