# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-17 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("previous", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
