# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-03-16 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("previous", "0002_player_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
