# Generated by Django 2.2.4 on 2022-02-04 17:00

from django.db import migrations, models


def set_my_defaults(apps, schema_editor):
    Activity = apps.get_model("previous", "Activity")
    for activity in Activity.objects.all().iterator():
        activity.url = activity.id
        activity.save()


class Migration(migrations.Migration):

    dependencies = [
        ("previous", "0003_activity_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="url",
            field=models.TextField(null=True),
        ),
        migrations.RunPython(set_my_defaults, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="activity",
            name="url",
            field=models.TextField(null=False, unique=True),
        ),
    ]
