# Generated by Django 4.2.15 on 2024-08-20 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('previous', '0004_activity_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='submittor',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='submittor',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='result',
            name='submittor',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='skillhistory',
            name='activity_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='previous.activity'),
            preserve_default=False,
        ),
    ]
