# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-15 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('previous', '0005_add_defaults'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ranking',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='skillhistory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='skilltype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'managed': True},
        ),
    ]
