# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('min_teams_per_match', models.IntegerField(default=1)),
                ('max_teams_per_match', models.IntegerField(null=True)),
                ('min_players_per_team', models.IntegerField(default=1)),
                ('max_players_per_team', models.IntegerField(default=1, null=True)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AdhocTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('mu', models.FloatField()),
                ('sigma', models.FloatField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.Activity')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated', models.IntegerField()),
                ('submittor', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='ResultSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ResultSetMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.Result')),
                ('result_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.ResultSet')),
            ],
        ),
        migrations.CreateModel(
            name='SkillHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mu', models.FloatField()),
                ('sigma', models.FloatField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.Activity')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.Player')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.Result')),
            ],
        ),
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_skill_range', models.FloatField(default=0.0)),
                ('max_skill_range', models.FloatField(default=50.0)),
                ('initial_mean', models.FloatField(default=25.0)),
                ('initial_std_dev', models.FloatField(default=8.333333333333334)),
                ('dynamics_factor', models.FloatField(default=0.08333333333333334)),
                ('skill_chain', models.FloatField(default=4.166666666666667)),
                ('draw_chance', models.FloatField(default=0.1)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validate', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.AdhocTeam')),
            ],
        ),
        migrations.AddField(
            model_name='adhocteam',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.Result'),
        ),
        migrations.AddField(
            model_name='activity',
            name='skill_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.SkillType'),
        ),
    ]
