name: tests

on:
  # Run this workflow every time a new commit or pull request is pushed to repo
  push:
  pull_request:
  # Allow workflow to be manually triggered
  workflow_dispatch:
  # Also run it once weekly to check for impact due to changes in the OS,
  # python, postgres, or any external packages/dependencies
  schedule:
  - cron: '7 14 * * fri'

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # Test with specific supported versions
          - name: supported
            os: ubuntu-20.04
            python: 3.8
            postgres: 10
          # Test everything with latest versions
          - name: latest
            os: ubuntu-latest
            python: 3.x
            postgres: latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install poetry
        shell: bash
        run: curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.4.2 python -
      - name: Install dependencies
        run: poetry install
      - name: Check for flake8 issues
        run: poetry run flake8 --exclude **/*/migrations/ rankings/
      - name: Check black formatting has been run
        run: poetry run black --check rankings/
      - name: Check for mypy typing issues
        run: poetry run mypy rankings/
      - name: Test database creation, migrations & data import
        run: |
          poetry run ./manage.py migrate \
            && poetry run ./manage.py loaddata game.json \
            && poetry run ./manage.py loaddata players.json
        working-directory: rankings
      - name: Run Django tests
        run: poetry run coverage run --source='.' manage.py test --debug-mode
        working-directory: rankings
      - name: Print coverage report
        run: poetry run coverage report
        working-directory: rankings
